"""Grounded nutrition knowledge base for the diet coach app.

Every food entry is intentionally simple and traceable so that
recommendations stay deterministic and free from hallucinations.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Sequence


@dataclass(frozen=True)
class FoodItem:
    key: str
    name: str
    serving: str
    calories: int
    protein_g: float
    carbs_g: float
    fat_g: float
    fiber_g: float
    categories: Sequence[str]
    micronutrients: Sequence[str]
    synonyms: Sequence[str]


FOOD_DB: Dict[str, FoodItem] = {
    "oats": FoodItem(
        key="oats",
        name="Rolled Oats",
        serving="40 g dry",
        calories=150,
        protein_g=5,
        carbs_g=27,
        fat_g=3,
        fiber_g=4,
        categories=("whole_grain", "complex_carbs"),
        micronutrients=("manganese", "phosphorus"),
        synonyms=("oats", "oatmeal", "porridge"),
    ),
    "greek_yogurt": FoodItem(
        key="greek_yogurt",
        name="Plain Greek Yogurt",
        serving="170 g cup",
        calories=100,
        protein_g=17,
        carbs_g=6,
        fat_g=0,
        fiber_g=0,
        categories=("lean_protein", "fermented"),
        micronutrients=("calcium", "probiotics"),
        synonyms=("greek yogurt", "yoghurt", "curd"),
    ),
    "banana": FoodItem(
        key="banana",
        name="Banana",
        serving="1 medium",
        calories=105,
        protein_g=1,
        carbs_g=27,
        fat_g=0,
        fiber_g=3,
        categories=("fruit",),
        micronutrients=("potassium", "vitamin B6"),
        synonyms=("banana", "plantain", "kela"),
    ),
    "apple": FoodItem(
        key="apple",
        name="Apple",
        serving="1 medium",
        calories=95,
        protein_g=0,
        carbs_g=25,
        fat_g=0,
        fiber_g=4,
        categories=("fruit",),
        micronutrients=("vitamin C", "polyphenols"),
        synonyms=("apple", "seb"),
    ),
    "spinach": FoodItem(
        key="spinach",
        name="Spinach",
        serving="1 cup cooked",
        calories=40,
        protein_g=5,
        carbs_g=7,
        fat_g=0,
        fiber_g=4,
        categories=("vegetable", "leafy_green"),
        micronutrients=("iron", "folate"),
        synonyms=("spinach", "palak"),
    ),
    "chickpeas": FoodItem(
        key="chickpeas",
        name="Cooked Chickpeas",
        serving="120 g cooked",
        calories=200,
        protein_g=11,
        carbs_g=35,
        fat_g=3,
        fiber_g=10,
        categories=("plant_protein", "legume", "fiber"),
        micronutrients=("folate", "magnesium"),
        synonyms=("chickpeas", "chana", "garbanzo"),
    ),
    "grilled_chicken": FoodItem(
        key="grilled_chicken",
        name="Grilled Chicken Breast",
        serving="100 g cooked",
        calories=165,
        protein_g=31,
        carbs_g=0,
        fat_g=4,
        fiber_g=0,
        categories=("lean_protein",),
        micronutrients=("niacin", "selenium"),
        synonyms=("chicken", "grilled chicken", "chicken breast"),
    ),
    "salmon": FoodItem(
        key="salmon",
        name="Baked Salmon",
        serving="100 g cooked",
        calories=208,
        protein_g=22,
        carbs_g=0,
        fat_g=13,
        fiber_g=0,
        categories=("healthy_fat", "lean_protein"),
        micronutrients=("omega-3", "vitamin D"),
        synonyms=("salmon", "fish"),
    ),
    "quinoa": FoodItem(
        key="quinoa",
        name="Cooked Quinoa",
        serving="140 g cooked",
        calories=170,
        protein_g=6,
        carbs_g=29,
        fat_g=3,
        fiber_g=3,
        categories=("whole_grain", "plant_protein"),
        micronutrients=("magnesium", "iron"),
        synonyms=("quinoa",),
    ),
    "brown_rice": FoodItem(
        key="brown_rice",
        name="Cooked Brown Rice",
        serving="150 g cooked",
        calories=165,
        protein_g=4,
        carbs_g=34,
        fat_g=1,
        fiber_g=2,
        categories=("whole_grain", "complex_carbs"),
        micronutrients=("manganese", "selenium"),
        synonyms=("brown rice", "brown basmati"),
    ),
    "lentil_soup": FoodItem(
        key="lentil_soup",
        name="Lentil Soup",
        serving="250 ml bowl",
        calories=190,
        protein_g=12,
        carbs_g=30,
        fat_g=3,
        fiber_g=8,
        categories=("plant_protein", "legume", "vegetable"),
        micronutrients=("iron", "folate"),
        synonyms=("dal", "lentil soup", "sambar"),
    ),
    "mixed_salad": FoodItem(
        key="mixed_salad",
        name="Mixed Vegetable Salad",
        serving="2 cups",
        calories=120,
        protein_g=4,
        carbs_g=14,
        fat_g=6,
        fiber_g=5,
        categories=("vegetable", "fiber"),
        micronutrients=("vitamin C", "vitamin K"),
        synonyms=("salad", "veg salad"),
    ),
    "almonds": FoodItem(
        key="almonds",
        name="Almonds",
        serving="28 g handful",
        calories=165,
        protein_g=6,
        carbs_g=6,
        fat_g=14,
        fiber_g=4,
        categories=("healthy_fat", "snack"),
        micronutrients=("vitamin E", "magnesium"),
        synonyms=("almonds", "badam"),
    ),
    "paneer": FoodItem(
        key="paneer",
        name="Paneer",
        serving="80 g",
        calories=200,
        protein_g=14,
        carbs_g=4,
        fat_g=15,
        fiber_g=0,
        categories=("vegetarian_protein", "healthy_fat"),
        micronutrients=("calcium", "vitamin A"),
        synonyms=("paneer", "cottage cheese"),
    ),
    "tofu": FoodItem(
        key="tofu",
        name="Firm Tofu",
        serving="90 g",
        calories=140,
        protein_g=15,
        carbs_g=5,
        fat_g=8,
        fiber_g=2,
        categories=("plant_protein", "healthy_fat"),
        micronutrients=("iron", "calcium"),
        synonyms=("tofu", "soy paneer"),
    ),
    "eggs": FoodItem(
        key="eggs",
        name="Boiled Eggs",
        serving="2 eggs",
        calories=150,
        protein_g=13,
        carbs_g=1,
        fat_g=10,
        fiber_g=0,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("choline", "vitamin D"),
        synonyms=("egg", "eggs", "anda"),
    ),
    "berries": FoodItem(
        key="berries",
        name="Mixed Berries",
        serving="125 g",
        calories=70,
        protein_g=1,
        carbs_g=17,
        fat_g=0,
        fiber_g=4,
        categories=("fruit", "antioxidant"),
        micronutrients=("anthocyanins", "vitamin C"),
        synonyms=("berries", "strawberry", "blueberry", "raspberry"),
    ),
    "sweet_potato": FoodItem(
        key="sweet_potato",
        name="Roasted Sweet Potato",
        serving="130 g",
        calories=112,
        protein_g=2,
        carbs_g=26,
        fat_g=0,
        fiber_g=4,
        categories=("complex_carbs", "vegetable"),
        micronutrients=("beta carotene", "potassium"),
        synonyms=("sweet potato", "shakarkandi"),
    ),
    "turmeric_milk": FoodItem(
        key="turmeric_milk",
        name="Turmeric Milk",
        serving="240 ml",
        calories=180,
        protein_g=8,
        carbs_g=20,
        fat_g=8,
        fiber_g=0,
        categories=("hydration", "functional_food"),
        micronutrients=("curcumin", "calcium"),
        synonyms=("turmeric milk", "haldi doodh", "golden milk"),
    ),
    "water": FoodItem(
        key="water",
        name="Water",
        serving="250 ml",
        calories=0,
        protein_g=0,
        carbs_g=0,
        fat_g=0,
        fiber_g=0,
        categories=("hydration",),
        micronutrients=(),
        synonyms=("water", "glass of water"),
    ),
    "idli": FoodItem(
        key="idli",
        name="Steamed Idli",
        serving="2 pieces",
        calories=132,
        protein_g=6,
        carbs_g=28,
        fat_g=1,
        fiber_g=2,
        categories=("breakfast", "fermented", "complex_carbs"),
        micronutrients=("iron", "B vitamins"),
        synonyms=("idli", "idlies"),
    ),
    "dosa_plain": FoodItem(
        key="dosa_plain",
        name="Plain Dosa",
        serving="1 medium",
        calories=168,
        protein_g=5,
        carbs_g=30,
        fat_g=4,
        fiber_g=2,
        categories=("breakfast", "fermented", "complex_carbs"),
        micronutrients=("iron", "potassium"),
        synonyms=("dosa", "plain dosa"),
    ),
    "masala_dosa": FoodItem(
        key="masala_dosa",
        name="Masala Dosa",
        serving="1 stuffed dosa",
        calories=250,
        protein_g=6,
        carbs_g=35,
        fat_g=8,
        fiber_g=4,
        categories=("breakfast", "complex_carbs", "vegetable"),
        micronutrients=("iron", "vitamin C"),
        synonyms=("masala dosa", "mysore masala"),
    ),
    "uttapam": FoodItem(
        key="uttapam",
        name="Vegetable Uttapam",
        serving="1 medium",
        calories=220,
        protein_g=7,
        carbs_g=36,
        fat_g=5,
        fiber_g=4,
        categories=("breakfast", "vegetable", "complex_carbs"),
        micronutrients=("vitamin C", "folate"),
        synonyms=("uttapam", "uttappa"),
    ),
    "poha": FoodItem(
        key="poha",
        name="Kanda Poha",
        serving="1 bowl",
        calories=180,
        protein_g=5,
        carbs_g=32,
        fat_g=5,
        fiber_g=3,
        categories=("breakfast", "complex_carbs", "vegetable"),
        micronutrients=("iron", "vitamin C"),
        synonyms=("poha", "aval upma"),
    ),
    "upma": FoodItem(
        key="upma",
        name="Vegetable Upma",
        serving="1 bowl",
        calories=210,
        protein_g=6,
        carbs_g=35,
        fat_g=6,
        fiber_g=4,
        categories=("breakfast", "complex_carbs", "vegetable"),
        micronutrients=("iron", "magnesium"),
        synonyms=("upma", "rava upma"),
    ),
    "thepla": FoodItem(
        key="thepla",
        name="Methi Thepla",
        serving="2 pieces",
        calories=220,
        protein_g=6,
        carbs_g=32,
        fat_g=8,
        fiber_g=5,
        categories=("whole_grain", "breakfast", "vegetable"),
        micronutrients=("iron", "fiber"),
        synonyms=("thepla", "methi thepla"),
    ),
    "dhokla": FoodItem(
        key="dhokla",
        name="Khaman Dhokla",
        serving="3 pieces",
        calories=150,
        protein_g=6,
        carbs_g=22,
        fat_g=4,
        fiber_g=3,
        categories=("snack", "fermented", "plant_protein"),
        micronutrients=("folate", "magnesium"),
        synonyms=("dhokla", "khaman"),
    ),
    "paratha_aloo": FoodItem(
        key="paratha_aloo",
        name="Aloo Paratha",
        serving="1 stuffed paratha",
        calories=290,
        protein_g=7,
        carbs_g=45,
        fat_g=10,
        fiber_g=6,
        categories=("complex_carbs", "vegetable", "breakfast"),
        micronutrients=("iron", "potassium"),
        synonyms=("aloo paratha", "stuffed paratha"),
    ),
    "chapati": FoodItem(
        key="chapati",
        name="Whole Wheat Chapati",
        serving="2 pieces",
        calories=180,
        protein_g=6,
        carbs_g=34,
        fat_g=3,
        fiber_g=6,
        categories=("whole_grain", "complex_carbs"),
        micronutrients=("iron", "fiber"),
        synonyms=("chapati", "roti", "phulka"),
    ),
    "naan": FoodItem(
        key="naan",
        name="Butter Naan",
        serving="1 piece",
        calories=260,
        protein_g=8,
        carbs_g=40,
        fat_g=7,
        fiber_g=3,
        categories=("refined_grain", "complex_carbs"),
        micronutrients=("iron",),
        synonyms=("naan", "butter naan"),
    ),
    "parotta": FoodItem(
        key="parotta",
        name="Kerala Parotta",
        serving="1 piece",
        calories=300,
        protein_g=6,
        carbs_g=40,
        fat_g=12,
        fiber_g=3,
        categories=("refined_grain", "snack"),
        micronutrients=("iron",),
        synonyms=("parotta", "paratha kerala"),
    ),
    "lemon_rice": FoodItem(
        key="lemon_rice",
        name="Lemon Rice",
        serving="1 cup",
        calories=210,
        protein_g=5,
        carbs_g=33,
        fat_g=7,
        fiber_g=3,
        categories=("complex_carbs", "vegetable"),
        micronutrients=("vitamin C", "iron"),
        synonyms=("lemon rice", "chitranna"),
    ),
    "curd_rice": FoodItem(
        key="curd_rice",
        name="Curd Rice",
        serving="1 cup",
        calories=230,
        protein_g=8,
        carbs_g=34,
        fat_g=6,
        fiber_g=1,
        categories=("complex_carbs", "fermented", "hydration"),
        micronutrients=("calcium", "probiotics"),
        synonyms=("curd rice", "thair sadam", "dahi chawal"),
    ),
    "khichdi": FoodItem(
        key="khichdi",
        name="Moong Dal Khichdi",
        serving="1 bowl",
        calories=240,
        protein_g=9,
        carbs_g=40,
        fat_g=5,
        fiber_g=5,
        categories=("whole_grain", "plant_protein", "comfort_food"),
        micronutrients=("iron", "magnesium"),
        synonyms=("khichdi", "kichri"),
    ),
    "veg_biryani": FoodItem(
        key="veg_biryani",
        name="Vegetable Biryani",
        serving="1 bowl",
        calories=320,
        protein_g=8,
        carbs_g=50,
        fat_g=10,
        fiber_g=6,
        categories=("complex_carbs", "vegetable"),
        micronutrients=("vitamin A", "iron"),
        synonyms=("veg biryani", "vegetable biriyani"),
    ),
    "chicken_biryani": FoodItem(
        key="chicken_biryani",
        name="Chicken Biryani",
        serving="1 bowl",
        calories=420,
        protein_g=22,
        carbs_g=50,
        fat_g=14,
        fiber_g=3,
        categories=("lean_protein", "complex_carbs"),
        micronutrients=("vitamin B12", "iron"),
        synonyms=("chicken biryani", "hyderabadi biryani"),
    ),
    "pulao": FoodItem(
        key="pulao",
        name="Veg Pulao",
        serving="1 cup",
        calories=260,
        protein_g=6,
        carbs_g=42,
        fat_g=7,
        fiber_g=4,
        categories=("complex_carbs", "vegetable"),
        micronutrients=("vitamin A",),
        synonyms=("pulao", "pilaf"),
    ),
    "dal_tadka": FoodItem(
        key="dal_tadka",
        name="Dal Tadka",
        serving="1 bowl",
        calories=210,
        protein_g=12,
        carbs_g=28,
        fat_g=6,
        fiber_g=6,
        categories=("plant_protein", "legume"),
        micronutrients=("folate", "iron"),
        synonyms=("dal tadka", "yellow dal"),
    ),
    "dal_makhani": FoodItem(
        key="dal_makhani",
        name="Dal Makhani",
        serving="1 bowl",
        calories=320,
        protein_g=15,
        carbs_g=32,
        fat_g=15,
        fiber_g=8,
        categories=("plant_protein", "healthy_fat"),
        micronutrients=("iron", "folate"),
        synonyms=("dal makhani", "maa ki dal"),
    ),
    "rajma": FoodItem(
        key="rajma",
        name="Rajma Curry",
        serving="1 bowl",
        calories=280,
        protein_g=14,
        carbs_g=37,
        fat_g=8,
        fiber_g=9,
        categories=("plant_protein", "legume"),
        micronutrients=("iron", "magnesium"),
        synonyms=("rajma", "kidney bean curry"),
    ),
    "chole": FoodItem(
        key="chole",
        name="Chole Masala",
        serving="1 bowl",
        calories=300,
        protein_g=14,
        carbs_g=40,
        fat_g=10,
        fiber_g=10,
        categories=("plant_protein", "legume", "fiber"),
        micronutrients=("folate", "zinc"),
        synonyms=("chole", "chana masala"),
    ),
    "sambar": FoodItem(
        key="sambar",
        name="Vegetable Sambar",
        serving="1 bowl",
        calories=160,
        protein_g=7,
        carbs_g=22,
        fat_g=4,
        fiber_g=5,
        categories=("vegetable", "legume", "hydration"),
        micronutrients=("vitamin C", "potassium"),
        synonyms=("sambar", "saambaar"),
    ),
    "rasam": FoodItem(
        key="rasam",
        name="Tomato Rasam",
        serving="1 bowl",
        calories=80,
        protein_g=3,
        carbs_g=12,
        fat_g=2,
        fiber_g=2,
        categories=("hydration", "vegetable"),
        micronutrients=("vitamin C", "electrolytes"),
        synonyms=("rasam", "charu"),
    ),
    "curd": FoodItem(
        key="curd",
        name="Homemade Curd",
        serving="200 g",
        calories=120,
        protein_g=7,
        carbs_g=9,
        fat_g=5,
        fiber_g=0,
        categories=("fermented", "hydration"),
        micronutrients=("calcium", "probiotics"),
        synonyms=("curd", "dahi", "yogurt"),
    ),
    "palak_paneer": FoodItem(
        key="palak_paneer",
        name="Palak Paneer",
        serving="1 bowl",
        calories=280,
        protein_g=14,
        carbs_g=16,
        fat_g=18,
        fiber_g=5,
        categories=("vegetarian_protein", "vegetable", "healthy_fat"),
        micronutrients=("iron", "calcium"),
        synonyms=("palak paneer", "spinach paneer"),
    ),
    "paneer_butter_masala": FoodItem(
        key="paneer_butter_masala",
        name="Paneer Butter Masala",
        serving="1 bowl",
        calories=360,
        protein_g=12,
        carbs_g=20,
        fat_g=26,
        fiber_g=4,
        categories=("vegetarian_protein", "healthy_fat"),
        micronutrients=("vitamin A", "calcium"),
        synonyms=("paneer butter masala", "shahi paneer"),
    ),
    "baingan_bharta": FoodItem(
        key="baingan_bharta",
        name="Baingan Bharta",
        serving="1 bowl",
        calories=200,
        protein_g=5,
        carbs_g=18,
        fat_g=12,
        fiber_g=6,
        categories=("vegetable", "healthy_fat"),
        micronutrients=("potassium", "fiber"),
        synonyms=("baingan bharta", "smoked eggplant"),
    ),
    "butter_chicken": FoodItem(
        key="butter_chicken",
        name="Butter Chicken",
        serving="1 bowl",
        calories=430,
        protein_g=28,
        carbs_g=14,
        fat_g=28,
        fiber_g=2,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("vitamin B12", "iron"),
        synonyms=("butter chicken", "murgh makhani"),
    ),
    "tandoori_chicken": FoodItem(
        key="tandoori_chicken",
        name="Tandoori Chicken",
        serving="2 pieces",
        calories=320,
        protein_g=36,
        carbs_g=6,
        fat_g=16,
        fiber_g=2,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("niacin", "selenium"),
        synonyms=("tandoori chicken", "grilled tandoori"),
    ),
    "fish_curry": FoodItem(
        key="fish_curry",
        name="Coastal Fish Curry",
        serving="1 bowl",
        calories=260,
        protein_g=24,
        carbs_g=6,
        fat_g=14,
        fiber_g=2,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("omega-3", "vitamin D"),
        synonyms=("fish curry", "meen curry"),
    ),
    "prawn_curry": FoodItem(
        key="prawn_curry",
        name="Prawn Curry",
        serving="1 bowl",
        calories=230,
        protein_g=24,
        carbs_g=8,
        fat_g=10,
        fiber_g=2,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("selenium", "vitamin B12"),
        synonyms=("prawn curry", "shrimp curry"),
    ),
    "rogan_josh": FoodItem(
        key="rogan_josh",
        name="Rogan Josh",
        serving="1 bowl",
        calories=380,
        protein_g=26,
        carbs_g=10,
        fat_g=26,
        fiber_g=2,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("iron", "vitamin B12"),
        synonyms=("rogan josh", "mutton curry"),
    ),
    "litti_chokha": FoodItem(
        key="litti_chokha",
        name="Litti Chokha",
        serving="2 litti + chokha",
        calories=360,
        protein_g=13,
        carbs_g=52,
        fat_g=12,
        fiber_g=8,
        categories=("whole_grain", "vegetable"),
        micronutrients=("iron", "fiber"),
        synonyms=("litti chokha", "litti"),
    ),
    "misal_pav": FoodItem(
        key="misal_pav",
        name="Misal Pav",
        serving="1 plate",
        calories=420,
        protein_g=16,
        carbs_g=50,
        fat_g=18,
        fiber_g=10,
        categories=("plant_protein", "snack"),
        micronutrients=("iron", "vitamin C"),
        synonyms=("misal pav", "misal"),
    ),
    "pav_bhaji": FoodItem(
        key="pav_bhaji",
        name="Pav Bhaji",
        serving="1 plate",
        calories=450,
        protein_g=12,
        carbs_g=60,
        fat_g=18,
        fiber_g=8,
        categories=("vegetable", "snack"),
        micronutrients=("vitamin A", "vitamin C"),
        synonyms=("pav bhaji", "bhaji"),
    ),
    "vada_pav": FoodItem(
        key="vada_pav",
        name="Vada Pav",
        serving="1 bun + vada",
        calories=290,
        protein_g=7,
        carbs_g=42,
        fat_g=10,
        fiber_g=5,
        categories=("snack", "complex_carbs"),
        micronutrients=("potassium",),
        synonyms=("vada pav", "wada pav"),
    ),
    "bhelpuri": FoodItem(
        key="bhelpuri",
        name="Bhelpuri",
        serving="1 bowl",
        calories=180,
        protein_g=5,
        carbs_g=30,
        fat_g=5,
        fiber_g=4,
        categories=("snack", "vegetable"),
        micronutrients=("vitamin C", "fiber"),
        synonyms=("bhelpuri", "bhel"),
    ),
    "pani_puri": FoodItem(
        key="pani_puri",
        name="Pani Puri",
        serving="6 puri",
        calories=180,
        protein_g=4,
        carbs_g=32,
        fat_g=5,
        fiber_g=3,
        categories=("snack", "hydration"),
        micronutrients=("electrolytes",),
        synonyms=("pani puri", "golgappa", "puchka"),
    ),
    "samosa": FoodItem(
        key="samosa",
        name="Veg Samosa",
        serving="1 piece",
        calories=180,
        protein_g=4,
        carbs_g=24,
        fat_g=8,
        fiber_g=3,
        categories=("snack", "vegetable"),
        micronutrients=("potassium",),
        synonyms=("samosa", "aloo samosa"),
    ),
    "pakora": FoodItem(
        key="pakora",
        name="Mixed Veg Pakora",
        serving="4 pieces",
        calories=220,
        protein_g=6,
        carbs_g=24,
        fat_g=12,
        fiber_g=4,
        categories=("snack", "vegetable", "plant_protein"),
        micronutrients=("iron",),
        synonyms=("pakora", "bhajiya", "fritter"),
    ),
    "kathi_roll": FoodItem(
        key="kathi_roll",
        name="Paneer Kathi Roll",
        serving="1 roll",
        calories=340,
        protein_g=15,
        carbs_g=38,
        fat_g=14,
        fiber_g=5,
        categories=("vegetarian_protein", "snack"),
        micronutrients=("calcium",),
        synonyms=("kathi roll", "frankie"),
    ),
    "seekh_kebab": FoodItem(
        key="seekh_kebab",
        name="Chicken Seekh Kebab",
        serving="2 skewers",
        calories=260,
        protein_g=22,
        carbs_g=4,
        fat_g=16,
        fiber_g=1,
        categories=("lean_protein", "snack"),
        micronutrients=("iron", "vitamin B12"),
        synonyms=("seekh kebab", "kabab"),
    ),
    "idiyappam": FoodItem(
        key="idiyappam",
        name="Idiyappam",
        serving="2 nests",
        calories=220,
        protein_g=4,
        carbs_g=46,
        fat_g=1,
        fiber_g=2,
        categories=("complex_carbs", "breakfast"),
        micronutrients=("iron",),
        synonyms=("idiyappam", "string hopper"),
    ),
    "appam": FoodItem(
        key="appam",
        name="Appam",
        serving="2 appam",
        calories=210,
        protein_g=4,
        carbs_g=38,
        fat_g=4,
        fiber_g=2,
        categories=("breakfast", "fermented", "complex_carbs"),
        micronutrients=("iron",),
        synonyms=("appam", "hoppers"),
    ),
    "veg_kurma": FoodItem(
        key="veg_kurma",
        name="Vegetable Kurma",
        serving="1 bowl",
        calories=240,
        protein_g=6,
        carbs_g=18,
        fat_g=16,
        fiber_g=5,
        categories=("vegetable", "healthy_fat"),
        micronutrients=("vitamin A", "potassium"),
        synonyms=("veg kurma", "korma"),
    ),
    "egg_curry": FoodItem(
        key="egg_curry",
        name="Egg Curry",
        serving="2 eggs + gravy",
        calories=280,
        protein_g=18,
        carbs_g=10,
        fat_g=18,
        fiber_g=2,
        categories=("lean_protein", "healthy_fat"),
        micronutrients=("choline", "vitamin D"),
        synonyms=("egg curry", "anda curry"),
    ),
    "bhindi_masala": FoodItem(
        key="bhindi_masala",
        name="Bhindi Masala",
        serving="1 bowl",
        calories=180,
        protein_g=5,
        carbs_g=18,
        fat_g=10,
        fiber_g=6,
        categories=("vegetable", "healthy_fat"),
        micronutrients=("vitamin K", "folate"),
        synonyms=("bhindi masala", "okra fry"),
    ),
    "tiffin_sambar": FoodItem(
        key="tiffin_sambar",
        name="Hotel Tiffin Sambar",
        serving="1 bowl",
        calories=190,
        protein_g=9,
        carbs_g=24,
        fat_g=6,
        fiber_g=6,
        categories=("vegetable", "legume", "hydration"),
        micronutrients=("vitamin C", "potassium"),
        synonyms=("tiffin sambar", "idli sambar"),
    ),
    "rasgulla": FoodItem(
        key="rasgulla",
        name="Rasgulla",
        serving="2 pieces",
        calories=220,
        protein_g=6,
        carbs_g=38,
        fat_g=4,
        fiber_g=0,
    categories=("dessert",),
        micronutrients=("calcium",),
        synonyms=("rasgulla", "rossogolla"),
    ),
    "gulab_jamun": FoodItem(
        key="gulab_jamun",
        name="Gulab Jamun",
        serving="2 pieces",
        calories=300,
        protein_g=6,
        carbs_g=50,
        fat_g=10,
        fiber_g=0,
        categories=("dessert", "snack"),
        micronutrients=("calcium",),
        synonyms=("gulab jamun", "gulabjam"),
    ),
    "jalebi": FoodItem(
        key="jalebi",
        name="Jalebi",
        serving="3 pieces",
        calories=310,
        protein_g=5,
        carbs_g=60,
        fat_g=8,
        fiber_g=1,
        categories=("dessert",),
        micronutrients=("iron",),
        synonyms=("jalebi", "imarti"),
    ),
    "kheer": FoodItem(
        key="kheer",
        name="Rice Kheer",
        serving="1 bowl",
        calories=280,
        protein_g=8,
        carbs_g=42,
        fat_g=9,
        fiber_g=1,
        categories=("dessert", "hydration"),
        micronutrients=("calcium", "vitamin B12"),
        synonyms=("kheer", "payasam"),
    ),
    "payasam": FoodItem(
        key="payasam",
        name="Ada Pradhaman",
        serving="1 bowl",
        calories=320,
        protein_g=7,
        carbs_g=45,
        fat_g=12,
        fiber_g=2,
        categories=("dessert", "healthy_fat"),
        micronutrients=("iron", "potassium"),
        synonyms=("payasam", "ada pradhaman"),
    ),
    "laddu": FoodItem(
        key="laddu",
        name="Besan Laddu",
        serving="2 pieces",
        calories=280,
        protein_g=7,
        carbs_g=28,
        fat_g=16,
        fiber_g=3,
        categories=("dessert", "healthy_fat"),
        micronutrients=("iron", "vitamin E"),
        synonyms=("laddu", "ladoo"),
    ),
    "halwa": FoodItem(
        key="halwa",
        name="Gajar Ka Halwa",
        serving="1 bowl",
        calories=290,
        protein_g=6,
        carbs_g=38,
        fat_g=12,
        fiber_g=4,
        categories=("dessert", "vegetable"),
        micronutrients=("vitamin A",),
        synonyms=("halwa", "gajar halwa"),
    ),
    "masala_chai": FoodItem(
        key="masala_chai",
        name="Masala Chai",
        serving="200 ml",
        calories=80,
        protein_g=2,
        carbs_g=12,
        fat_g=3,
        fiber_g=0,
        categories=("hydration", "beverage"),
        micronutrients=("antioxidants",),
        synonyms=("masala chai", "chai"),
    ),
    "filter_coffee": FoodItem(
        key="filter_coffee",
        name="South Indian Filter Coffee",
        serving="150 ml",
        calories=60,
        protein_g=2,
        carbs_g=8,
        fat_g=2,
        fiber_g=0,
        categories=("hydration", "beverage"),
        micronutrients=("antioxidants",),
        synonyms=("filter coffee", "kaapi"),
    ),
    "mango_lassi": FoodItem(
        key="mango_lassi",
        name="Mango Lassi",
        serving="250 ml",
        calories=260,
        protein_g=9,
        carbs_g=40,
        fat_g=8,
        fiber_g=2,
        categories=("hydration", "dessert"),
        micronutrients=("vitamin A", "calcium"),
        synonyms=("mango lassi", "lassi"),
    ),
    "salted_buttermilk": FoodItem(
        key="salted_buttermilk",
        name="Salted Buttermilk",
        serving="250 ml",
        calories=90,
        protein_g=6,
        carbs_g=10,
        fat_g=3,
        fiber_g=0,
        categories=("hydration", "fermented"),
        micronutrients=("calcium", "electrolytes"),
        synonyms=("chaas", "buttermilk", "neer mor"),
    ),
    "coconut_water": FoodItem(
        key="coconut_water",
        name="Tender Coconut Water",
        serving="250 ml",
        calories=45,
        protein_g=2,
        carbs_g=11,
        fat_g=0,
        fiber_g=1,
        categories=("hydration", "electrolyte"),
        micronutrients=("potassium", "magnesium"),
        synonyms=("coconut water", "nariyal pani"),
    ),
    "sugarcane_juice": FoodItem(
        key="sugarcane_juice",
        name="Sugarcane Juice",
        serving="250 ml",
        calories=180,
        protein_g=0,
        carbs_g=45,
        fat_g=0,
        fiber_g=0,
        categories=("hydration", "beverage"),
        micronutrients=("iron", "zinc"),
        synonyms=("sugarcane juice", "ganne ka ras"),
    ),
}


CATEGORY_TARGETS: Dict[str, int] = {
    "vegetable": 3,
    "fruit": 2,
    "whole_grain": 2,
    "lean_protein": 3,
    "plant_protein": 2,
    "healthy_fat": 2,
    "hydration": 8,  # glasses of water/fluids
}


def all_food_items() -> List[FoodItem]:
    return list(FOOD_DB.values())


def get_food(key: str) -> FoodItem | None:
    return FOOD_DB.get(key)


def find_matches(label: str) -> List[FoodItem]:
    """Return foods whose synonyms include the label substring."""
    normalized = label.lower().strip()
    results: List[FoodItem] = []
    for item in FOOD_DB.values():
        for synonym in item.synonyms:
            if normalized in synonym.lower() or synonym.lower() in normalized:
                results.append(item)
                break
    return results


def best_guess(label: str) -> FoodItem | None:
    matches = find_matches(label)
    return matches[0] if matches else None
